from todo.views.delete_task import delete_task
from todo.views.external_add import external_add
from todo.views.list_detail import list_detail
from todo.views.list_lists import list_lists
from todo.views.task_lists import task_lists  
from todo.views.accepted_petitions import accepted_petitions
from todo.views.users_management import users_management 
from todo.views.books_management import books_management
from todo.views.book_edit import book_edit
from todo.views.users_detail import users_detail
from todo.views.add_user import add_user
from todo.views.remove_attachment import remove_attachment
from todo.views.reorder_tasks import reorder_tasks
from todo.views.search import search
from todo.views.task_detail import task_detail
from todo.views.toggle_done import toggle_done
from todo.views.book_assign import book_assign
from todo.views.book_publish import book_publish
from todo.views.book_detail import book_detail
from todo.views.set_ft_pass import set_ft_pass
from todo.views.change_password import change_password
from todo.views.designer_assign import designer_assign
from todo.views.book_catalogue import book_catalogue
from todo.views.book_category import book_category
from todo.views.create_subscription import create_subscription
from todo.views.cancel_subscription import cancel_subscription
from todo.views.profile import profile
from todo.views.main import main
from todo.views.deactivate_user import deactivate_user
from todo.views.activate_user import activate_user
from todo.views.deactivate_book import deactivate_book
from todo.views.activate_book import activate_book
from todo.views.download_book import download_book